# Generated by Django 5.1.6 on 2025-05-19 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_student_phone_student_place_alter_student_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[A-Za-z]+$')])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('place', models.CharField(error_messages='the place field contain only letter and max length 50', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
